// Generated by scripts/generate-tsrx-types.mjs.
import type { DefinitionItemNode as DefinitionItemNodeType, ListItemNode as ListItemNodeType, ParsedNode, TableRowNode as TableRowNodeType } from 'stream-markdown-parser';
import type { HtmlPreviewFrameProps } from '../components/CodeBlockNode/HtmlPreviewFrame.tsrx';
import type { TooltipProps } from '../components/Tooltip/Tooltip.tsrx';
import type { HtmlComponentMap, StreamingComponentMap } from '../customComponents';
import type { NodeRendererProps, RenderContext } from '../types';
import type { CodeBlockNodeProps, D2BlockNodeProps, ImageNodeProps, InfographicBlockNodeProps, LinkNodeProps, MathBlockNodeProps, MathInlineNodeProps, MermaidBlockNodeProps, PreCodeNodeProps } from '../types/component-props';
import type { NodeComponentProps } from '../types/node-component';
import * as Octane from 'octane';
export declare function TextNode(props: NodeComponentProps<{
    type: 'text';
    content: string;
    center?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function ParagraphNode(props: NodeComponentProps<{
    type: 'paragraph';
    children?: ParsedNode[];
}>): Octane.ElementDescriptor<{}>;
export declare function HeadingNode(props: NodeComponentProps<{
    type: 'heading';
    level?: number;
    children?: ParsedNode[];
    attrs?: Record<string, string | boolean>;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function BlockquoteNode(props: NodeComponentProps<{
    type: 'blockquote';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function ListItemNode(props: NodeComponentProps<{
    type: 'list_item';
    children?: ParsedNode[];
}> & {
    value?: number;
}): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function ListNode(props: NodeComponentProps<{
    type: 'list';
    ordered?: boolean;
    start?: number;
    items?: ListItemNodeType[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function TableNode(props: NodeComponentProps<{
    type: 'table';
    header?: TableRowNodeType;
    rows?: TableRowNodeType[];
    loading?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function DefinitionListNode(props: NodeComponentProps<{
    type: 'definition_list';
    items?: DefinitionItemNodeType[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function FootnoteNode(props: NodeComponentProps<{
    type: 'footnote';
    id: string;
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function FootnoteReferenceNode(props: NodeComponentProps<{
    type: 'footnote_reference';
    id: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function FootnoteAnchorNode(props: NodeComponentProps<{
    type: 'footnote_anchor';
    id: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function AdmonitionNode(props: NodeComponentProps<{
    type: 'admonition';
    kind?: string;
    title?: string;
    children?: ParsedNode[];
    collapsible?: boolean;
    open?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function CheckboxNode(props: NodeComponentProps<{
    type: 'checkbox' | 'checkbox_input';
    checked?: boolean;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function EmojiNode(props: NodeComponentProps<{
    type: 'emoji';
    name: string;
    markup?: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function StrongNode(props: NodeComponentProps<{
    type: 'strong';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function EmphasisNode(props: NodeComponentProps<{
    type: 'emphasis';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function StrikethroughNode(props: NodeComponentProps<{
    type: 'strikethrough';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function HighlightNode(props: NodeComponentProps<{
    type: 'highlight';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function InsertNode(props: NodeComponentProps<{
    type: 'insert';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function SubscriptNode(props: NodeComponentProps<{
    type: 'subscript';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function SuperscriptNode(props: NodeComponentProps<{
    type: 'superscript';
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function HardBreakNode(_props: NodeComponentProps<{
    type: 'hardbreak';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function ThematicBreakNode(_props?: NodeComponentProps<{
    type: 'thematic_break';
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function InlineCodeNode(props: NodeComponentProps<{
    type: 'inline_code';
    code: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function LinkNode(props: NodeComponentProps<LinkNodeProps['node']> & {
    showTooltip?: boolean;
    color?: string;
    underlineHeight?: number;
    underlineBottom?: number | string;
    animationDuration?: number;
    animationOpacity?: number;
    animationTiming?: string;
    animationIteration?: string | number;
}): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function ImageNode(rawProps: ImageNodeProps): import("octane/jsx-runtime").Octane.JSX.Element | null;
export declare function PreCodeNode({ node }: PreCodeNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function CodeBlockNode(props: CodeBlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function MermaidBlockNode(props: MermaidBlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function D2BlockNode(props: D2BlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function InfographicBlockNode(props: InfographicBlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function MathBlockNode({ node }: MathBlockNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function MathInlineNode({ node }: MathInlineNodeProps): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function ReferenceNode(props: NodeComponentProps<{
    type: 'reference';
    id: string;
}> & {
    messageId?: string;
    threadId?: string;
}): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function HtmlBlockNode(props: NodeComponentProps<{
    type: 'html_block';
    content?: string;
    tag?: string;
    attrs?: [string, string | null][] | null;
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element | Octane.ElementDescriptor<{
    [x: string]: unknown;
}>;
export declare function HtmlInlineNode(props: NodeComponentProps<{
    type: 'html_inline';
    content?: string;
    tag?: string;
    attrs?: [string, string | null][] | null;
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element | Octane.ElementDescriptor<Record<string, import("stream-markdown-parser").HtmlPropValue>>;
export declare function VmrContainerNode(props: NodeComponentProps<{
    type: 'vmr_container';
    name: string;
    attrs?: Record<string, string> | [string, string | null][] | null;
    children?: ParsedNode[];
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function Tooltip(_props: TooltipProps): null;
export declare function HtmlPreviewFrame(_props: HtmlPreviewFrameProps): null;
export declare function FallbackComponent(props: NodeComponentProps<{
    type: string;
}>): import("octane/jsx-runtime").Octane.JSX.Element;
export declare function renderNode(node: ParsedNode, key: string | number | bigint, ctx: RenderContext): Octane.OctaneNode;
export declare function NodeRenderer<TStreamingComponents extends StreamingComponentMap = StreamingComponentMap, THtmlComponents extends Record<string, any> = HtmlComponentMap>(props: NodeRendererProps<TStreamingComponents, THtmlComponents>): import("octane/jsx-runtime").Octane.JSX.Element;
export { CodeBlockNode as OctaneCodeBlockNode };
export default NodeRenderer;
