packages:
  - playground
  - playground-angular
  - playground-next14
  - playground-next15
  - playground-vue2
  - playground-vue2-cli
  - playground-nuxt
  - playground-octane
  - playground-react18
  - playground-react19
  - playground-svelte
  - playground-solid
  - packages/*
